apiVersion: v1
kind: Service
metadata:
  name: node-demo-service
  labels:
    app: node-demo
spec:
  selector:
    app: node-demo
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
